// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojmwznedyfosvcbrgixx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qbXd6bmVkeWZvc3ZjYnJnaXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MDE1MjIsImV4cCI6MjA1Mjk3NzUyMn0.TJAAnmIC539SWyUWIWvH5alKmMJUq_RtoMwedNzMlS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);